### ISSUE TITLE
Error downloading the dataset fetch_x5

### ISSUE THREAD

**Issue by CristhianBoujon** [maks-sh/scikit-uplift#195]
## To Reproduce

1. Open notebooks/RetailHero_EN.ipynb
2. Excecute cells including until 
```
dataset = fetch_x5()
dataset.keys()
```
3. it raises the following exception
![Captura de Pantalla 2022-08-10 a la(s) 17 50 16](https://user-images.githubusercontent.com/1195235/184017493-91f2b27f-cfcc-4687-88e4-e43fc921baa7.png)

4. I have tried to run with no success:
```
import sklift.datasets as ds
ds.clear_data_dir()

```

## Expected behavior
I expect to download the dataset with success.

## Environment
I'm using Google collaboratory environment

 - scikit-uplift: version 0.5.0
 - scikit-learn version: 1.0.2
 - Python version: 3.7.13
 - OS (e.g., Linux): Ubuntu, 18.04.6 LTS (Bionic Beaver)

**Comment by maks-sh** [comment]
Hello, Cristhian!

Thanks for the good description of issue.

Indeed, there is an error in the [code](https://github.com/maks-sh/scikit-uplift/blob/master/sklift/datasets/datasets.py#L324). In this checker we should `csv_purchase_path` instead of `csv_clients_path`.

Today I will try to fix it and release a new version.

**Comment by maks-sh** [comment]
It seems that these messages are not different? 🤔

Now the message looks like [this](https://github.com/maks-sh/scikit-uplift/blob/fix_x5_error/sklift/datasets/datasets.py#L333).

**Comment by maks-sh** [comment]
Now it should work in 0.5.1 version.

If you have an idea about exception message, please let me know. We add it in new release.
