### ISSUE TITLE
Qini curve

### ISSUE THREAD

**Issue by Garve** [maks-sh/scikit-uplift#53]
## 🐛 Bug

Hi! first of all, great project. I just noticed something weird with the qini curve.
![grafik](https://user-images.githubusercontent.com/932327/106753350-da7a3100-662b-11eb-8977-f88c7d90fb9c.png)
The model should never be able to surpass the red line, right?

## To Reproduce

```
from sklift.models import SoloModel
from sklift.viz import plot_qini_curve
from lightgbm import LGBMRegressor
import numpy as np

X = np.random.randn(100000, 2)
t = (X[:, 0] + X[:, 1] > 0.5)
y = X[:, 0]*X[:, 1] + 2*t + np.random.randn(100000)

s = SoloModel(LGBMRegressor())
s.fit(X, y, t)

plot_qini_curve(y, s.predict(X), t)
```

## Environment

 - scikit-uplift version: 0.2.0
 - lightgbm version: 3.1.1
 - Python version: 3.7.7
 - OS: Windows 10
 - Any other relevant information:

Thank for your work!

Best regards
Robert

**Comment by maks-sh** [comment]
Hi, Robert!

Thank you for your feedback.

Nice pic 🙂 

Unfortunately, there is no such option as Qini curve for continious outcomes in sklift for now. The reason is that it differs from Qini curve for the binary outcome. For instance, there is no optimal Qini curve for the continious case (please see Radcliff, 2007 paper). So, we should add a checker that the target is binary.

I hope we will release a new version soon.

**Comment by Garve** [comment]
Hi Maksim!

Ah I see, that's true! Thanks :)

Best regards
Robert
